//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDirectoryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListingCategory()
        {
            this.ListingAndCategories = new HashSet<ListingAndCategory>();
        }
    
        public int ListingCategoryId { get; set; }
        public string CategoryName { get; set; }
        public System.DateTime Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingAndCategory> ListingAndCategories { get; set; }
    }
}
