//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDirectoryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingAndCategory
    {
        public int ListingAndCategoryId { get; set; }
        public int ListingId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Listing Listing { get; set; }
        public virtual ListingCategory ListingCategory { get; set; }
    }
}
